print('-----Calculating Exponenets----')
print('\t')
print('\t')
base = int(input('Enter an interger as the base value:'))
exponent = int(input('Enter an interger as the exponent:'))
print('\t')
print('\t')
print(base,'raised to the power of',exponent,'is',base*exponent)
print('\t')
print('\t')
print('-----Addition and Subtraction----')
print('\t')
print('\t')
start = int(input('Enter a starting interger:'))
add = int(input('Enter an interger to add:'))
sub = int(input('Enter an interger to subtract:'))
print('\t')
print('\t')
print(start,'+',add,'-',sub,'is equal to',start + add - sub)
while True:
    pass
